// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <Arduino.h>
#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
extern char wifi_ssid[32];
extern char wifi_password[32];

const char * get_wifi_ssid();
const char * get_wifi_password();

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_homelabel;
extern lv_obj_t * ui_Parameter;
extern lv_obj_t * ui_giaidoan;
extern lv_obj_t * ui_timeelapsed;
extern lv_obj_t * ui_timeremaining;
extern lv_obj_t * ui_inputstatus;
extern lv_obj_t * ui_wifilabel;
extern lv_obj_t * ui_mqttlabel;
extern lv_obj_t * ui_statustemp;
extern lv_obj_t * ui_statushumi;
extern lv_obj_t * ui_tempalarm;
extern lv_obj_t * ui_poweralarm;
extern lv_obj_t * ui_lossphasealarm;
extern lv_obj_t * ui_outputstatus;
extern lv_obj_t * ui_dehumidifierfan;
extern lv_obj_t * ui_humipump;
extern lv_obj_t * ui_convectionfan;
extern lv_obj_t * ui_heating;
void ui_event_Startbnt(lv_event_t * e);
extern lv_obj_t * ui_Startbnt;
extern lv_obj_t * ui_startLabel;
extern lv_obj_t * ui_Stopbnt;
extern lv_obj_t * ui_stopLabel;
void ui_event_Settingbnt(lv_event_t * e);
extern lv_obj_t * ui_Settingbnt;
extern lv_obj_t * ui_settingLabel;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_fvtemp;
extern lv_obj_t * ui_pvtemp;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_humilabel;
extern lv_obj_t * ui_fvhumi;
extern lv_obj_t * ui_pvhumi;
extern lv_obj_t * ui_Chart2;
#ifdef __cplusplus
void sendParameterToSlave(const String &type);
#endif

void ui_event_Startbnt(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_optionprocess;
extern lv_obj_t * ui_processlabel;
extern lv_obj_t * ui_templabel1;
extern lv_obj_t * ui_humdlabel;
extern lv_obj_t * ui_timelabel;
void ui_event_tempsetting1(lv_event_t * e);
extern lv_obj_t * ui_tempsetting1;
void ui_event_humdsetting1(lv_event_t * e);
extern lv_obj_t * ui_humdsetting1;
void ui_event_timesetting1(lv_event_t * e);
extern lv_obj_t * ui_timesetting1;
void ui_event_tempsetting2(lv_event_t * e);
extern lv_obj_t * ui_tempsetting2;
void ui_event_humdsetting2(lv_event_t * e);
extern lv_obj_t * ui_humdsetting2;
void ui_event_timesetting2(lv_event_t * e);
extern lv_obj_t * ui_timesetting2;
void ui_event_tempsetting3(lv_event_t * e);
extern lv_obj_t * ui_tempsetting3;
void ui_event_humdsetting3(lv_event_t * e);
extern lv_obj_t * ui_humdsetting3;
void ui_event_timesetting3(lv_event_t * e);
extern lv_obj_t * ui_timesetting3;
void ui_event_tempsetting4(lv_event_t * e);
extern lv_obj_t * ui_tempsetting4;
void ui_event_humdsetting4(lv_event_t * e);
extern lv_obj_t * ui_humdsetting4;
void ui_event_timesetting4(lv_event_t * e);
extern lv_obj_t * ui_timesetting4;
void ui_event_okbnt(lv_event_t * e);
extern lv_obj_t * ui_okbnt;
extern lv_obj_t * ui_Label13;
void ui_event_cancelbnt(lv_event_t * e);
extern lv_obj_t * ui_cancelbnt;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES
static void dropdown_event_handler(lv_event_t * e);

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_parameterbnt(lv_event_t * e);
extern lv_obj_t * ui_parameterbnt;
extern lv_obj_t * ui_Label15;
void ui_event_wifibnt(lv_event_t * e);
extern lv_obj_t * ui_wifibnt;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_historybnt;
extern lv_obj_t * ui_Label3;
void ui_event_backbnt(lv_event_t * e);
extern lv_obj_t * ui_backbnt;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
void ui_event_idtext(lv_event_t * e);
extern lv_obj_t * ui_idtext;
void ui_event_passtext(lv_event_t * e);
extern lv_obj_t * ui_passtext;
extern lv_obj_t * ui_statuswf;
extern lv_obj_t * ui_wifiname;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_hmiupdatebnt;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_hmiversion;
extern lv_obj_t * ui_statusupdate1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_programupdatebnt;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_statusupdate2;
extern lv_obj_t * ui_programversion;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;
void ui_event_KeyBoard1(lv_event_t * e);
// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Small_Font);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
