// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xDFDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_optionprocess = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_optionprocess, "\nOption 2\nOption 3");
    lv_obj_set_width(ui_optionprocess, 221);
    lv_obj_set_height(ui_optionprocess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_optionprocess, 3);
    lv_obj_set_y(ui_optionprocess, -167);
    lv_obj_set_align(ui_optionprocess, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_optionprocess, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_processlabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_processlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_processlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_processlabel, -184);
    lv_obj_set_y(ui_processlabel, -167);
    lv_obj_set_align(ui_processlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_processlabel, "Process:");
    lv_obj_set_style_text_font(ui_processlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempsetting = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_tempsetting, 175);
    lv_obj_set_height(ui_tempsetting, 44);
    lv_obj_set_x(ui_tempsetting, 2);
    lv_obj_set_y(ui_tempsetting, -90);
    lv_obj_set_align(ui_tempsetting, LV_ALIGN_CENTER);

    ui_templabel1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_templabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_templabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_templabel1, -221);
    lv_obj_set_y(ui_templabel1, -90);
    lv_obj_set_align(ui_templabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_templabel1, "Temperature:");
    lv_obj_set_style_text_font(ui_templabel1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humdlabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_humdlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humdlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humdlabel, -196);
    lv_obj_set_y(ui_humdlabel, -19);
    lv_obj_set_align(ui_humdlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humdlabel, "Humidity:");
    lv_obj_set_style_text_font(ui_humdlabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humdsetting = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_humdsetting, 175);
    lv_obj_set_height(ui_humdsetting, 44);
    lv_obj_set_x(ui_humdsetting, 3);
    lv_obj_set_y(ui_humdsetting, -17);
    lv_obj_set_align(ui_humdsetting, LV_ALIGN_CENTER);

    ui_timesetting = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_timesetting, 175);
    lv_obj_set_height(ui_timesetting, 44);
    lv_obj_set_x(ui_timesetting, 4);
    lv_obj_set_y(ui_timesetting, 57);
    lv_obj_set_align(ui_timesetting, LV_ALIGN_CENTER);

    ui_timelabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_timelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timelabel, -166);
    lv_obj_set_y(ui_timelabel, 56);
    lv_obj_set_align(ui_timelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timelabel, "Time:");
    lv_obj_set_style_text_font(ui_timelabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_okbnt = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_okbnt, 100);
    lv_obj_set_height(ui_okbnt, 50);
    lv_obj_set_x(ui_okbnt, -93);
    lv_obj_set_y(ui_okbnt, 160);
    lv_obj_set_align(ui_okbnt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okbnt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_okbnt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_okbnt, lv_color_hex(0x00BA0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okbnt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_okbnt);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "OK");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbnt = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_cancelbnt, 100);
    lv_obj_set_height(ui_cancelbnt, 50);
    lv_obj_set_x(ui_cancelbnt, 100);
    lv_obj_set_y(ui_cancelbnt, 160);
    lv_obj_set_align(ui_cancelbnt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbnt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cancelbnt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cancelbnt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbnt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_cancelbnt);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 1);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "CANCEL");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_okbnt, ui_event_okbnt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbnt, ui_event_cancelbnt, LV_EVENT_ALL, NULL);

}
